### ISSUE TITLE
Post a Summary on GitHub

### ISSUE THREAD

**Issue by smarr** [smarr/ReBenchDB#30]
It would be great if ReBenchDB could post a summary of the performance evaluation on GitHub.

Though, there are a few issues to figure out in terms of the design first.

#### Needed Data

A sketch of how to post a comment is here: https://gist.github.com/smarr/317e83149bb564e54dc2b662a312ae03

The needed data is:
 - [x] commit SHA (got it via `Source.commitId`
 - [x] GitHub repo (got it via `Source.repoUrl`)
 - [x] a baseline to compare to

#### Baseline

The baseline could be selected via project configuration.
It could be:
 1. the main/dev branch, where we take the last known result at the time (using `Source.branchOrTag`)
 2. if there's a PR (requires extra work), we could take the branch against which it is to be merged
 3. last commit for which there's a data set
    - this is initially the base branch, but after it will be the previous version on the branch
 4. last commit which is also on the master branch

The two options that likely cover most questions would be 1. and 4.
Sometimes, the differential to the previous, i.e. option 3. might also be useful.

The benefit of option 2. and variations would be that it requires less configuration, but that's perhaps something for the future. It's also an issue because we can't assume that there's always a PR, but we'd still want the performance summary.

For now, let's go with option 1.

#### A Trigger

A trigger for posting the comment:

 1. received new data
    - problems: it's cumulative, but GitHub will notify immediately when comment is posted
    - we could update a comment, or have cumulative results, though that seems annoying (many notifications)
    - relying on timeouts will delay notification and make this likely unusable

 2. a trial was completed (i.e., an execution of ReBench completed)
    - problems: it's also cumulative (an experiment can have multiple ReBench executions to get all needed data)

 3. a full experiment completed (there's currently no concept like this)
    - needs an extra signal to ReBench, possibly an extra command for ReBench something like `rebench --report-completion rebench.conf`

Seems like option 3 would be the most immediate (no delays), but requires an extra complication in rebench.

#### TODO

 - [x] add configuration for baseline branch
 - [x] build trigger to signal compilation into rebench
 - [x] determine latest commitId for `branchOrTag == config.mainBranch && commitId != mergedCommit`

**Comment by smarr** [comment]
Resolved an merged with #31.
